version: "3.4"
services:
  # frontend-dev:
  #   build:
  #     context: ./packages/frontend
  #     target: dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   stdin_open: true
  #   command: yarn start
  # frontend:
  #   build:
  #     context: ./packages/frontend
  #     target: prod
  #   ports:
  #     - "80:80"
  #   image: tolicodes/zoomevents-frontend
  backend:
    build:
      context: ./packages/backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=zoomevents
      - PORT=4000
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    image: tolicodes/zoomevents-backend
  # storybook:
  #   build:
  #     context: ./packages/frontend
  #     target: dev
  #   ports:
  #     - "9009:9009"
  #   command: yarn storybook
  #   volumes:
  #     - ./packages/frontend:/app
  #     - /app/node_modules
  #   image: tolicodes/zoomevents-storybook
  db:
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: zoomevents
    volumes:
      - $HOME/docker/volumes/zoomevents/mysql/:/var/lib/mysql/
    image: mysql:5.7
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=123
    command: --default-authentication-plugin=mysql_native_password
